added animation
xaolaw/Dissertation pull request #69
Opened 2023-11-02 18:58 UTC by xDominix

2023-11-02 19:02 UTC, Michal-Szewc requested changes
![image](https://github.com/xaolaw/Dissertation/assets/92829528/b5bc9397-1e09-42f1-a763-7e58b1daf80e)
jest pasek z boku (wadliwy produkt)

2023-11-02 20:48 UTC, Michal-Szewc commented
pasowało by bez ustawień edytora i użytkownika... no i wersja projektu ta sama, chyba że grupowo istalimy

2023-11-03 10:58 UTC, xaolaw requested changes
Błąd białego ekranu przejścia nie wypełnia całego canvasu 
![image](https://github.com/xaolaw/Dissertation/assets/92537069/6b938af3-410d-4cbb-b312-507f14112f81)

2023-11-04 18:34 UTC, xaolaw approved these changes
Jest git

2023-11-04 18:36 UTC, merged